name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Clone Org-mode exporter
      run: git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo

    - name: Clone tomelr
      run: git clone https://github.com/kaushalmodi/tomelr.git tomelr

    - name: Setup emacs
      uses: purcell/setup-emacs@master
      with:
        version: 26.3

    - name: Emacs dir setup
      run: mkdir -p ~/.emacs.d/ && touch ~/.emacs.d/.org-id-locations

    - name: Export Posts Org file to Markdown
      run: emacs ./post/*.org --batch -L ../tomelr -L ../ox-hugo -l ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill

    - name: Export Misc Org file to Markdown
      run: emacs ./post/*.org --batch -L ../tomelr -L ../ox-hugo -l ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.119.0'

    - name: Build
      run: hugo --minify --theme=hermit

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

permissions:
  contents: read
  pages: write
  id-token: write
